INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4251);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1693);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4198);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3236);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1700);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3854);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4034);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3438);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (466);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2138);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2445);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3297);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3145);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3188);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (675);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2003);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2025);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2708);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2654);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4779);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3096);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3961);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3765);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2568);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2393);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2936);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3231);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4944);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3188);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4232);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3859);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4579);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2386);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3507);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1835);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2196);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1868);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4499);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2900);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1111);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2351);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2453);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (634);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1378);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3425);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (820);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4204);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4108);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2436);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4615);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2276);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (197);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4294);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2252);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (772);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (656);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2329);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4029);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3849);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1949);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2947);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3919);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4952);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1933);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3761);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4390);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (468);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (178);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4148);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4927);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1677);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3223);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3752);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4236);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4413);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (419);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3232);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1979);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1414);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4788);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2804);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1329);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (801);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2154);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1831);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2812);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (824);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4077);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2941);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2750);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2981);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4220);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3945);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2900);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1123);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3985);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (661);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2752);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (127);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4832);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1964);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1472);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4809);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3102);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (495);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2158);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2935);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4026);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4908);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3414);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3849);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3484);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1320);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4768);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1738);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2069);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (702);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3365);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3623);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (848);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2911);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2206);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3906);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2819);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (926);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4028);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3555);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (737);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2242);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3501);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4746);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3668);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3496);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (982);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4973);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3423);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3765);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3277);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (984);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2301);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1086);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (830);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2432);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (509);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3277);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3430);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1740);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4542);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1352);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2748);