INSERT INTO FONE_CLINICA (FONE)
VALUES ('90525-6356');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('92565-1132');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('98290-7215');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('97261-7131');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('94844-2327');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('91280-8215');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('91525-7760');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('92218-4347');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('93297-8162');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('92881-2036');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('93435-4323');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('99964-3910');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('95532-0951');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('97654-0858');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('97292-2403');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('98829-3912');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('91641-9439');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('97334-1212');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('99734-3957');
INSERT INTO FONE_CLINICA (FONE)
VALUES ('92639-4641');

-- ----------------------------

INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90752-4726');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96833-2698');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91236-6486');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98197-5743');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96923-6318');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92853-7462');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93334-9872');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98755-4821');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92994-7335');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98322-6480');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91727-4375');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('99606-3887');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93858-8931');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96216-5432');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92737-6957');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96467-8157');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94847-7347');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91885-3411');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95465-7638');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93716-5839');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97667-6521');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90682-3863');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96287-6770');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98188-2446');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91226-3413');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98473-5758');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92493-9892');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96348-4541');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97775-8139');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92557-5047');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91761-9766');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98634-8127');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94862-9856');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94728-4588');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92701-7839');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94719-1366');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92150-7994');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98230-1008');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98747-9293');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96283-4141');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97689-6446');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90187-6428');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91681-2451');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97579-9375');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98818-3178');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98449-1764');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98143-9855');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96532-6315');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93158-9863');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91996-6120');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96445-6188');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94266-9412');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98149-1186');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97161-7387');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93110-8534');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91872-0962');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96409-8142');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91151-1697');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95437-3011');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92207-2616');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98684-5872');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97625-5614');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92762-1738');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93730-5487');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93486-8352');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93616-6704');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91291-6797');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98785-4571');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94337-5313');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90321-5248');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94626-8688');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('99970-2446');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95865-4275');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97113-5562');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98821-0855');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93713-9464');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91182-5401');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96643-3371');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96016-3472');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91081-4244');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94181-8131');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96883-5249');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97664-2844');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94137-9945');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92885-3260');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92736-1358');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94701-3741');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90398-7342');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98123-1923');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98684-5467');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93009-7451');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93048-8218');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95211-7632');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91736-3046');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96674-1151');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90446-8815');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96631-9835');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91601-5735');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94598-7517');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94533-6311');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94627-7101');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92416-4671');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97580-6203');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96518-7423');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90064-4658');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92042-3434');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97328-1811');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91861-4667');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92121-1819');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96637-9127');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98192-4215');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95088-4910');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91194-6563');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92064-2878');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95156-7236');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93270-3551');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95538-4800');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97355-2823');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90637-4633');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93018-4011');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93627-5685');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98316-6563');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95124-9759');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91682-5891');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92525-7091');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93986-7327');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93441-5164');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('94026-1952');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97087-1650');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91116-7563');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97231-4257');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93483-6546');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91346-4374');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91345-0626');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97271-1176');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('98363-8463');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97537-0538');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('95955-3343');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('90122-4401');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('96016-4705');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97911-0487');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('97828-4514');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('93234-5135');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91648-3844');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92520-6451');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('92340-5545');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91423-6350');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91278-2342');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('99937-5561');
INSERT INTO FONE_FUNCIONARIO (FONE)
VALUES ('91151-1241');

-- -------------------------------------------

INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96642-5767');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93110-1623');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91126-7385');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94263-0754');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94186-7362');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95813-1135');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98528-6406');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96086-8216');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95236-4452');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90636-4347');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91684-7481');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96127-3427');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93156-6381');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92427-7889');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94384-7208');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90971-3685');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91347-6072');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91505-5343');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91486-3573');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91401-1469');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92644-1786');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91666-8814');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94028-9277');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('99966-7508');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90458-4463');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93046-3022');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96663-3457');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96175-7371');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97808-2121');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96722-8435');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93655-2267');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91886-5858');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97168-5261');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93973-6379');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94943-4343');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('99457-6667');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98201-5574');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91584-3877');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96297-2228');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92757-5190');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98619-2661');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96524-6398');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91308-3318');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97236-9221');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91367-3141');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98132-4882');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91628-5998');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93690-6589');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96172-4225');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90815-4936');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97362-3557');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95584-8425');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97312-1792');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95535-6116');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93832-4215');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96749-3310');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93262-1718');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91832-6657');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98138-4626');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94282-5369');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('99803-6515');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91351-2922');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97512-6386');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98946-2042');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94692-2763');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98599-2530');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91858-9071');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95155-3777');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94735-4137');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97562-6688');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93423-3585');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96815-5513');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('99079-1831');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97410-1132');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93387-6767');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90744-4422');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96958-2006');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92976-1218');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94921-0452');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98741-7983');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97263-8559');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94158-2458');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98195-8635');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92157-8126');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('96698-6464');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91446-8461');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('92266-8132');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98852-8327');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91405-6404');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('94866-6496');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('99356-1438');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91841-7937');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98532-2626');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('91238-7547');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('98931-8296');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('97787-2507');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90623-4937');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('95384-6255');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('90546-7629');
INSERT INTO FONE_PACIENTE (FONE)
VALUES ('93757-1422');

-- -------------------------------------------------

INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('arcu@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sit.amet.consectetuer@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('suspendisse@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ridiculus@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('eget.mollis@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('morbi.sit@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('velit.dui@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('pellentesque.tellus@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('condimentum.eget.volutpat@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('integer.vitae@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dictum.mi.ac@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ligula@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tempus.mauris.erat@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ac.risus.morbi@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sit.amet@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ullamcorper.velit@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('amet.metus.aliquam@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('quis.pede@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('scelerisque.neque@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('a.enim@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dolor.vitae@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ultrices@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('vel.turpis@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sed.nunc@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dolor.fusce@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aliquam.fringilla.cursus@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ipsum.non.arcu@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('id.enim.curabitur@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tristique.pharetra@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('eget@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('luctus.ut@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nulla@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('mauris.eu@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('congue.a@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sed.eget@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('convallis.erat@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('cursus.in.hendrerit@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nulla.ante@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sollicitudin.a.malesuada@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tincidunt@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tristique.pellentesque@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('curabitur.ut.odio@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('suspendisse.commodo@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('risus.varius@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('egestas.urna@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('pretium.aliquet.metus@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('praesent.eu.nulla@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('montes.nascetur@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('commodo@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('lacus.aliquam.rutrum@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('blandit.viverra.donec@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ullamcorper@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('egestas.fusce.aliquet@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('etiam.ligula@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('eget.magna@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('volutpat.nulla.facilisis@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ad.litora@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('non.sollicitudin@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ac.turpis@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ligula.eu@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('posuere.at@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('fusce.aliquet@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('a.feugiat.tellus@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('etiam@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('mauris.vel.turpis@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('praesent.luctus@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('erat.sed@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('eget.varius.ultrices@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('in.tincidunt.congue@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('enim@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('et.arcu.imperdiet@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aliquam.tincidunt.nunc@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('proin.velit@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('proin.ultrices.duis@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('orci.luctus.et@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('faucibus.lectus.a@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('arcu.vestibulum@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('arcu.vestibulum@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('fringilla.ornare.placerat@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aliquet.libero@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dui.cum@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('non.leo@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('montes@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ut.quam@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('risus.morbi.metus@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nec.ante@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('quisque.imperdiet.erat@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('interdum.nunc.sollicitudin@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nascetur.ridiculus@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dapibus.gravida@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('blandit.at@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('arcu.iaculis@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('luctus.curabitur.egestas@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('integer.aliquam@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('donec.non@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('pellentesque.sed@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('at.sem@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('donec.sollicitudin.adipiscing@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('in@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('mattis.semper@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('vivamus.nisi.mauris@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ligula.nullam@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nibh.enim@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('in@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sed.nunc@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dictum.eu@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ut.nulla.cras@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('luctus@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('gravida.mauris.ut@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('lorem.eu@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sed.auctor@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tellus.aenean@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sem.egestas@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('vulputate.dui.nec@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('suspendisse.aliquet.molestie@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ipsum@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('phasellus@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('at.auctor.ullamcorper@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('proin.nisl@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ullamcorper.magna@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('lectus.quis.massa@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('amet.diam@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('at.egestas@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('faucibus.orci@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ipsum.nunc@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('fermentum.vel@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('pede.ac.urna@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('cras.interdum@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nisi.a@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('dapibus.gravida@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('metus.vivamus.euismod@yahoo.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('justo.praesent.luctus@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('purus.mauris.a@hotmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('massa@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nascetur@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nec.tempus.scelerisque@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aliquet.nec@gmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('metus.aenean.sed@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tellus.justo.sit@ufpe.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aliquam@yahoo.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('quisque.nonummy.ipsum@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ipsum.primis@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sagittis.placerat@hotmail.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('nibh.enim@ufpe.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('ipsum.donec.sollicitudin@outlook.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('sed@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('aenean.eget@gmail.br');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('mauris@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('a.malesuada.id@outlook.com');
INSERT INTO EMAIL_FUNCIONARIO (EMAIL)
VALUES ('tristique.pharetra@outlook.com');

-- ----------------------------------------------

INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('magnis.dis.parturient@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ac@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('urna.nunc@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('porttitor.tellus.non@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lectus.convallis.est@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('diam.eu@gmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('odio.auctor.vitae@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('maecenas.iaculis.aliquet@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nec.malesuada.ut@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('sed.dui@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('laoreet.posuere@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('facilisis.eget@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('aliquam.ultrices@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('praesent.luctus.curabitur@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('duis@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ut.pellentesque@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('at@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('in@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('id.ante@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('natoque.penatibus.et@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ut.erat.sed@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quisque@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nibh.lacinia.orci@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('luctus.curabitur@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('dui@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('fringilla.cursus@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('et.magnis@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('amet@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quis.urna@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('a.aliquet.vel@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('sit@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('laoreet.posuere@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('non.feugiat@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('sollicitudin.orci.sem@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quis@gmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nunc.ullamcorper@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('curae.donec@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ipsum@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('augue.sed@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('vivamus.nisi@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('dignissim.lacus.aliquam@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('neque.nullam@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ac.arcu.nunc@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quam.curabitur@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('accumsan.neque@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nunc@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lacus.cras@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('arcu.sed@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('parturient@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('pede@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('donec.consectetuer@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ullamcorper@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('et.lacinia@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('semper.et@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('magna.ut@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('vestibulum.ante@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ipsum.primis.in@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('a.odio@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('a.facilisis.non@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ac@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('sit.amet.nulla@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lacus.cras@gmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('integer@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('aliquam.adipiscing@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('aliquam.nisl.nulla@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('magna.lorem.ipsum@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nullam.velit@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('imperdiet.non.vestibulum@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('faucibus.leo@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quis@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('eu@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('erat.nonummy@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('scelerisque.lorem@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('quisque.varius@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('pede@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('vehicula.et.rutrum@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('massa.lobortis.ultrices@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('sollicitudin@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('suspendisse.tristique@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('felis.purus.ac@gmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('integer@hotmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lorem@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('risus.duis@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lorem@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('molestie.tellus@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('nullam@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('adipiscing@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ligula.aenean@yahoo.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('tempus.mauris@gmail.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('fusce.fermentum@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('ullamcorper.duis@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('enim.sed.nulla@ufpe.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('aliquet@ufpe.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('proin.vel.nisl@outlook.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('velit@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('cras.dolor.dolor@outlook.com');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('est.mauris@yahoo.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('tortor.nibh@gmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('vestibulum@hotmail.br');
INSERT INTO EMAIL_PACIENTE (EMAIL)
VALUES ('lacus.cras@outlook.com');
