INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
