-- Data Definition Language (DDL)

-- TIPOS DE VARIÁVEIS:
-- CHAR(tamanho)
-- VARCHAR(tamanho)
-- DECIMAL(total, decimais)
-- DATE
-- DATETIME

-- Contraints: 
-- PRIMARY KEY, FOREIGN KEY AND UNIQUE (COLUNAS)
-- CHECK (EXPRESSÃO)

-- RESTRICT | NO ACTION | CASCADE | SET NULL | SET DEFAULT

-------------------------------------------------------------

-- CRIAR TABELA PESQUISADOR
CREATE TABLE PESQUISADOR (
  CPF VARCHAR(13),
  NOME VARCHAR(80) CONSTRAINT NN_PESQ_NOME NOT NULL,
  INSTITUICAO VARCHAR(80) NOT NULL,
  NASCIMENTO DATE,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (CPF),
  CONSTRAINT AK_USU_CPF UNIQUE (NOME, NASCIMENTO)
);

-- CRIAR TABELA EVENTO
CREATE TABLE EVENTO(
  COD VARCHAR(4) PRIMARY KEY,
  NOME VARCHAR(80) NOT NULL, 
  SIGLA VARCHAR(10) NOT NULL UNIQUE,
  ANO NUMBER(4)
);

-- CRIAR TABELA ARTIGO
CREATE TABLE ARTIGO(
  MAT VARCHAR(4),
  TITULO VARCHAR(80) NOT NULL,
  NOTA NUMBER(4,2) NOT NULL,
  IDIOMA VARCHAR(15) DEFAULT 'PORTUGUES',
  COD VARCHAR(4),
  CONSTRAINT PK_ARTIGO PRIMARY KEY (MAT),
  CONSTRAINT FK_ART_EVE FOREIGN KEY (COD) REFERENCES EVENTO (COD),
  CONSTRAINT CHK_ART_NOTA CHECK (NOTA BETWEEN 0 AND 10)
);

-- CRIAR TABELA ESCREVE
CREATE TABLE ESCREVE (
  CPF VARCHAR(4),
  MAT VARCHAR(4),
  CONSTRAINT ESCREVE_PK PRIMARY KEY (CPF, MAT),
  CONSTRAINT ESCREVE_PESQUISADOR_FK FOREIGN KEY (CPF)
    REFERENCES PESQUISADOR ON DELETE CASCADE,
  CONSTRAINT ESCREVE_ARTIGO_FK FOREIGN KEY (MAT)
    REFERENCES ARTIGO ON DELETE CASCADE
);

-- CRIANDO UMA TABELA A PARTIR DE UMA CONSULTA
CREATE TABLE MELHORES_ARTIGOS AS SELECT * FROM ARTIGO WHERE NOTA >= 9;

-----------------------------------------------------------------------

-- CRIAÇÃO DE INDICES:

-- Tabela tem muitas linhas.
-- Contém inúmeros valores distintos.
-- Coluna é muito usada para filtros (consultada).
-- Coluna sofre pouca atualização (CPF).

CREATE INDEX idx_usu_nome ON PESQUISADOR (NOME);
-- DROP INDEX idx_usu_nome;

-----------------------------------------------------------------------

-- CRIAÇÃO DE SEQUÊNCIAS:

CREATE SEQUENCE CONTAR
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CONTARNEGATIVO
START WITH 0
INCREMENT BY -1;

DROP SEQUENCE CONTARNEGATIVO;

-- Utilização:
-- INSERT INTO ARTIGO (MAT, TITULO, NOTA, IDIOMA) 
-- VALUES (NEXT VALUE FOR CONTAR, 'XPTO', 9, 'PORTUGUES');

-----------------------------------------------------------------------

-- CRIAÇÃO DE VIEWS:

-- Manipulação: Não tem diferença com a tabela
-- Mas uma VIEW não tem dados, somente se chamada.

CREATE VIEW MELHORES_ARTIGOS_PT AS SELECT *
  FROM ARTIGO
  WHERE NOTA >= 9 AND IDIOMA = 'PORTUGUES'

DROP VIEW MELHORES_ARTIGOS_PT;